function j_a = SymXJacobianEuler6DoF(in1,in2,mass,L,in5,max_thrust)
%SymXJacobianEuler6DoF
%    J_A = SymXJacobianEuler6DoF(IN1,IN2,MASS,L,IN5,MAX_THRUST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Apr-2025 14:57:37

I1 = in5(1,:);
I2 = in5(2,:);
I3 = in5(3,:);
T1 = in2(1,:);
T2 = in2(2,:);
T3 = in2(3,:);
gamma1 = in2(4,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
w1 = in1(10,:);
w2 = in1(11,:);
w3 = in1(12,:);
t2 = cos(gamma1);
t3 = cos(theta1);
t4 = cos(theta2);
t5 = cos(theta3);
t6 = sin(theta1);
t7 = sin(theta2);
t8 = sin(theta3);
t10 = -I2;
t11 = -I3;
t12 = 1.0./I1;
t13 = 1.0./I2;
t14 = 1.0./I3;
t17 = 1.0./mass;
t9 = t4.^2;
t15 = t5.*w3;
t16 = t8.*w2;
t18 = t3.*t5;
t19 = t3.*t8;
t20 = t5.*t6;
t21 = t6.*t8;
t22 = 1.0./t7;
t24 = I1+t10;
t25 = I1+t11;
t26 = I2+t11;
t23 = t22.^2;
t27 = t4.*t21;
t28 = t4.*t18;
t29 = t4.*t19;
t30 = t4.*t20;
t31 = -t27;
t32 = -t28;
t33 = t19+t30;
t34 = t20+t29;
t35 = t18+t31;
t36 = t21+t32;
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t17.*(-T2.*max_thrust.*t34+T3.*max_thrust.*t36+T1.*max_thrust.*t3.*t7),t2.*t17.*(-T3.*max_thrust.*t33+T2.*max_thrust.*t35+T1.*max_thrust.*t6.*t7),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t17.*(-T1.*max_thrust.*t7+T3.*max_thrust.*t4.*t5+T2.*max_thrust.*t4.*t8),t2.*t17.*(T1.*max_thrust.*t4.*t6+T2.*max_thrust.*t7.*t21+T3.*max_thrust.*t7.*t20),-t2.*t17.*(T1.*max_thrust.*t3.*t4+T2.*max_thrust.*t7.*t19+T3.*max_thrust.*t7.*t18),-t4.*t15.*t23-t4.*t16.*t23,0.0];
mt2 = [t15+t16+t9.*t15.*t23+t9.*t16.*t23,0.0,0.0,0.0,0.0,0.0,0.0,t2.*t17.*(T2.*max_thrust.*t5.*t7-T3.*max_thrust.*t7.*t8),-t2.*t17.*(T2.*max_thrust.*t33+T3.*max_thrust.*t35),-t2.*t17.*(T3.*max_thrust.*t34+T2.*max_thrust.*t36),t5.*t22.*w2-t8.*t22.*w3,-t15-t16,-t4.*t5.*t22.*w2+t4.*t8.*t22.*w3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-t13.*t25.*w3,t14.*t24.*w2,0.0,0.0,0.0,0.0,0.0,0.0,t8.*t22,t5,-t4.*t8.*t22,t12.*t26.*w3,0.0,t14.*t24.*w1,0.0,0.0,0.0,0.0,0.0,0.0,t5.*t22,-t8,-t4.*t5.*t22,t12.*t26.*w2,-t13.*t25.*w1,0.0];
j_a = reshape([mt1,mt2],12,12);
end
